{% set version = "0.4.1" %}

package:
  name: ipywebrtc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywebrtc/ipywebrtc-{{ version }}.tar.gz
  sha256: f43679b11ef3b3801fd0a81523d917f93ac1fcd5a52e5f5cf6031bf1d65774ca

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ipywidgets >=7.4

test:
  imports:
    - ipywebrtc

about:
  home: https://github.com/maartenbreddels/ipywebrtc
  license: MIT
  license_file: LICENSE
  summary: 'WebRTC for Jupyter notebook/lab'
  doc_url: https://ipywebrtc.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipywebrtc

extra:
  recipe-maintainers:
    - maartenbreddels
    - martinRenou
