{% set version = "0.4.2" %}

package:
  name: ipywebrtc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywebrtc/ipywebrtc-{{ version }}.tar.gz
  sha256: c3cd1e863d91168680fabb76980d9b81a75e6970aa89dab3130dbc25dc13e377

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ipywidgets >=7.4

test:
  imports:
    - ipywebrtc

about:
  home: https://github.com/maartenbreddels/ipywebrtc
  license: MIT
  license_file: LICENSE
  summary: 'WebRTC for Jupyter notebook/lab'
  doc_url: https://ipywebrtc.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipywebrtc

extra:
  recipe-maintainers:
    - maartenbreddels
    - martinRenou
