{% set version = "0.6.0" %}

package:
  name: ipywebrtc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywebrtc/ipywebrtc-{{ version }}.tar.gz
  sha256: f8ac3cc02b3633b59f388aef67961cff57f90028fd303bb3886c63c3d631da13

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging
  run:
    - python >=3.6
    - ipywidgets >=7.6
    - numpy

test:
  imports:
    - ipywebrtc
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-webrtc/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-webrtc/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-webrtc/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-webrtc\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-webrtc\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-webrtc\\package.json (exit 1)          # [win]

about:
  home: https://github.com/maartenbreddels/ipywebrtc
  license: MIT
  license_file: LICENSE
  summary: 'WebRTC for Jupyter notebook/lab'
  doc_url: https://ipywebrtc.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipywebrtc

extra:
  recipe-maintainers:
    - maartenbreddels
    - martinRenou
