appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: R0AofTZyx874LxVl9Dslp6zLneoDvTRsO+LDMFIQrDHdXTROG9GnjLD3Rc6Qbq7QEFR4YU4IfEeYLhgwWeElB9ErUNvfdfs3SHPSPX1W7lpl/wpWAz247Di7pKpI/6MG8cE6j+3pKEctDQNlt5HhWIVPxU2E8unA5BD/5KgSL/PWZibh9xUed/GhNZOkaKVAsyk506OOkrdeLkJfnKYShASB61m5yZxY169h/MY1DQJdrpx7BCYPOuiFgcoHrp83fPfUtRNSxr6sHtVBAUicser62kuZAlyKkNp0y3nsHLlFNyg3GGZ/UgQIiSc5hIPcp1sg836m5JMjhuOPkTb2T+ysCHMsO+i/kEQZ1a2b/FmkSZyBhZz88lN5qhnhTxQqybhYfOgmShfvyLBy9HXGho6jrx8hVrL2PBcmkCFWL7Kt9KlDDXX9/Qle1XvXwhG1QkvY/Rk6NjUp/oRjHmdIUGgTgwKsVWJjJG6WzcG63sM2QrSh92Fgusn+c2cXUCYwA10cHriF9UcHw9RSCZ5zHP/FaTM8nRAb72Hl1GApVerLeFxjwf1pd86MWvURMs+kN9tAGGFueTyAIn4avge68iMIbAssdLpxe7yA/U2XbPHGT0Gc/FAlRHpKaWdoUTptd39fH9YuP999VEPfYqrO4zJtlFb/WpvHNF8g7iecxgQ=}
provider:
  win: azure
